# Generated by Django 4.2 on 2025-11-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'laboratorista',
            },
        ),
    ]
