# Generated by Django 4.2 on 2025-11-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_paciente', '0001_initial'),
        ('api_laboratorista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPerfilLipidico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colesterol_total', models.FloatField()),
                ('colesterol_hdl', models.FloatField()),
                ('colesterol_ldl', models.FloatField()),
                ('trigliceridos', models.FloatField()),
                ('fecha_analisis', models.DateField()),
                ('observaciones', models.TextField()),
                ('laboratorista', models.ForeignKey(db_column='laboratorista_id', on_delete=django.db.models.deletion.CASCADE, to='api_laboratorista.laboratorista')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='api_paciente.paciente')),
            ],
            options={
                'db_table': 'resultado_perfil_lipidico',
            },
        ),
    ]
