# Generated by Django 4.2 on 2025-11-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('codigo_ingreso', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('insurance', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
